[project]
name = "task-tracker"
version = "0.1.0"
description = "Task Tracker - A CLI app to track your tasks and manage your to-do list"
readme = "README.md"
requires-python = ">=3.7"
dependencies = []
